export const FETCH_STOCK_DATA_SUCCESS = 'FETCH_STOCK_DATA_SUCCESS';
export const FETCH_STOCK_DATA_FAILURE = 'FETCH_STOCK_DATA_FAILURE';
export const FETCH_AVAILABLE_SYMBOLS_SUCCESS = 'FETCH_AVAILABLE_SYMBOLS_SUCCESS';
export const FETCH_AVAILABLE_SYMBOLS_FAILURE = 'FETCH_AVAILABLE_SYMBOLS_FAILURE';
